# simple GET request to list all albums
GET {{host}}/albums
Accept: application/json

###

POST {{host}}/albums
Content-Type: application/json

{
  "id": "4",
  "title": "OK Computer",
  "artist": "Radiohead",
  "price": 99.99
}

###

GET {{host}}/albums/2
Accept: application/json

###

GET {{host}}/stats
Accept: application/json